### ISSUE TITLE
ImportError: No module named google.protobuf

### ISSUE THREAD

**Issue by TheColin21** [pawliczka/CRX3-Creator#4]
I just tried to convert an older extension of mine and got the following:

`Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import crx3_pb2
  File "/mnt/d/__INSTALL/ChromeTheme/CRX3-Creator/crx3_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor`

This also appears, when I try to pack the sample folder. I installed all requirements (or at least I ran pip install -r requirements.txt)

**Comment by pawliczka** [comment]
pip uninstall protobuf
pip uninstall google
pip install google
pip install protobuf
